# Generated by Django 4.1.13 on 2024-08-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='salary_slips/'),
        ),
    ]
